# Generated by Django 4.1.9 on 2023-08-16 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_bookstudy'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bookstudy',
            options={'ordering': ['id']},
        ),
        migrations.AddField(
            model_name='user',
            name='study_groups',
            field=models.ManyToManyField(to='api.bookstudy'),
        ),
    ]
